E-Bus.Presentation/Controllers/TripsController.cs
using E_Bus.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTOs;
using ServiceContracts.DTOs.ReservationDTO;

namespace E_Bus.Presentation.Controllers
{
    [Route("[controller]/[action]")]
    public class TripsController : Controller
    {
        private readonly ITripsService _tripsService;
        private readonly IReservationService _reservationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public TripsController(ITripsService tripsService, IReservationService reservationService, UserManager<ApplicationUser> userManager)
        {
            _tripsService = tripsService;
            _reservationService = reservationService;
            _userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> UpcomingTrips()
        {
            return View(await _tripsService.GetUpcomingTripsAsync());
        }

        [AllowAnonymous]
        [HttpGet("{tripId:guid}")]
        public async Task<IActionResult> TripDetails(Guid tripId)
        {
            return View(await _tripsService.GetTripByIdAsync(tripId, true));
        }

    }
}

E-Bus.Presentation/Views/Shared/Layout.cshtml
<!DOCTYPE HTML>

<html>
<head>
    <title>@($"E-Bus | {ViewBag.Title}")</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/StyleSheet.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" asp-fallback-href="~/FontAwesome/all.min.css" asp-fallback-test-class="fab" asp-fallback-test-property="font-style" asp-fallback-test-value="normal" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" asp-action="Index" asp-controller="Home"><i class="fa-solid fa-bus"></i>E-Bus</a>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="Home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="UpcomingTrips" asp-controller="Trips">Upcoming Trips</a>
                    </li>
                    @if (User is not null && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Trips" asp-action="AddTrip" asp-area="admin">
                                Add Trip
                            </a>
                        </li>
                    }
                    @if (User is not null && User.IsInRole("User"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Trips" asp-action="MyReservations" asp-area="user" >
                                My Reservations
                            </a>
                        </li>
                    }
                </ul>
                <div class="d-flex">
                    <ul class="navbar-nav">
                        @if (User is not null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link active" aria-current="page"><i class="fa-solid fa-circle-user" style="margin-right:0.25vw"></i>@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post">
                                    <button type="submit" class="btn btn-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Login" asp-area="" method="get">
                                    <button type="submit" class="btn btn-dark">Login</button>
                                </form>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Register" asp-area="" method="get">
                                    <button type="submit" class="btn btn-dark">Register</button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    @RenderBody()

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous" asp-fallback-test="window.bootstrap" asp-fallback-src="~/Bootstrap/bootstrap.bundle.min.js" referrerpolicy="no-referrer"></script>
    @RenderSection("jsSection", required:false)
</body>
</html>