E-Bus.Presentation/Areas/Admin/Controllers/TripsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ServiceContracts;
using ServiceContracts.DTOs;
using ServiceContracts.DTOs.TripDTO;

namespace E_Bus.Presentation.Areas.Admin.Controllers
{



    [Route("[area]/[controller]/[action]")]
    [Area("admin")]
    [Authorize(Roles = "Admin")]
    public class TripsController : Controller
    {
        private readonly ITransportationsService transportationsService;
        private readonly ITripsService tripService;



        public TripsController(ITransportationsService transportationsService, ITripsService tripService)
        {
            this.transportationsService = transportationsService;
            this.tripService = tripService;
        }

        [HttpGet]
        public async Task<IActionResult> AddTrip()
        {
            var transportations = await transportationsService.GetAllAsync();
            
            if(transportations is null) { /* Redirect to create Transportation*/ }

            ViewBag.Means = transportations.Select(t => new SelectListItem() { Text=t.Name , Value= t.Id.ToString()});


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTrip(TripAddRequest tripAddRequest)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(e => e.Errors).Select(e => e.ErrorMessage.ToString());
                var errorsString = string.Join("\n-", errors);
                ViewBag.Errors = errorsString;
                var transportations = await transportationsService.GetAllAsync();

                if (transportations is null) { /* Redirect to create Transportation*/ }

                ViewBag.Means = transportations.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() });
                return View(tripAddRequest);
            }

            if (!await tripService.AddTripAsync(tripAddRequest))
            {
                ViewBag.Errors = "Trip failed to be saved.";
                var transportations = await transportationsService.GetAllAsync();

                if (transportations is null) { /* Redirect to create Transportation*/ }

                ViewBag.Means = transportations.Select(t => new SelectListItem() { Text = t.Name, Value = t.Id.ToString() });
                return View(tripAddRequest);
            }

            return RedirectToAction(actionName: "UpcomingTrips", controllerName: "Trips", routeValues: new { area = null as string});
        }

    }
}

E-Bus.Presentation/Areas/User/Controllers/TripsController.cs
using E_Bus.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTOs.ReservationDTO;
using ServiceContracts.DTOs;

namespace E_Bus.Presentation.Areas.User.Controllers
{
    [Route("[area]/[controller]/[action]")]
    [Area("user")]
    [Authorize(Roles = "User")]
    public class TripsController : Controller
    {
        private readonly ITripsService _tripsService;
        private readonly IReservationService _reservationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public TripsController(ITripsService tripsService, IReservationService reservationService, UserManager<ApplicationUser> userManager)
        {
            _tripsService = tripsService;
            _reservationService = reservationService;
            _userManager = userManager;
        }

        [HttpGet("{tripId:guid}")]
        public async Task<IActionResult> RegisterTrip(Guid tripId)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user is null)
            {
                return StatusCode(400);
            }
            if (await _reservationService.GetReservationById($"{tripId}{user.Id}", false) is not null)
            {
                ViewBag.Errors = "You can't register more than once for same trip.";
                return View();
            }
            ReservationResponse userTripWrapperModel = new ReservationResponse()
            {
                TheTripResponse = await _tripsService.GetTripByIdAsync(tripId, true),
                TheUserDTO = user.ToUserDTO()
            };

            if (userTripWrapperModel.TheTripResponse is null || userTripWrapperModel.TheUserDTO is null) { return StatusCode(400); }

            return View(userTripWrapperModel);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterPostTrip([FromForm] ReservationAddRequest reservationAddRequest)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(e => e.Errors).Select(e => e.ErrorMessage.ToString());
                var errorsString = string.Join("\n-", errors);
                ViewBag.Errors = errorsString;
                return RedirectToAction(nameof(RegisterTrip), "Trips", routeValues: new { area = "user", tripId = reservationAddRequest.TripId });
            }

            if (!await _reservationService.AddReservationAsync(reservationAddRequest))
            {

                return RedirectToAction(nameof(RegisterTrip), "Trips", routeValues: new { area = "user", tripId = reservationAddRequest.TripId });
            }
            //Go to Ticket Page
            return RedirectToAction(actionName: nameof(ShowReservation), controllerName: "Trips", routeValues: new { area = "user", tripId = reservationAddRequest.TripId, userId = reservationAddRequest.UserId });
        }

        [HttpGet("{TripId:guid}/{UserId:guid}")]
        public async Task<IActionResult> ShowReservation([FromRoute] ReservationId reservationId)
        {
            var userTripWrapperModel = await _reservationService.GetReservationById($"{reservationId.TripId}{reservationId.UserId}");

            if (userTripWrapperModel is null || userTripWrapperModel.TheTripResponse is null || userTripWrapperModel.TheUserDTO is null) { return StatusCode(400); }

            return View(userTripWrapperModel);
        }

        [HttpGet("{TripId:guid}/{UserId:guid}")]
        public async Task<IActionResult> ShowPdf([FromRoute] ReservationId reservationId)
        {
            var userTripWrapperModel = await _reservationService.GetReservationById($"{reservationId.TripId}{reservationId.UserId}");

            if (userTripWrapperModel is null || userTripWrapperModel.TheTripResponse is null || userTripWrapperModel.TheUserDTO is null) { return StatusCode(400); }

            return new ViewAsPdf(viewName: "ShowPdf", viewData: ViewData, model: userTripWrapperModel)
            {
                ContentType = "application/pdf",
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
                PageMargins = new Rotativa.AspNetCore.Options.Margins()
                {
                    Top = 3,
                    Bottom = 3,
                    Left = 3,
                    Right = 3
                }
            };
        }

        [HttpGet]
        public async Task<IActionResult> MyReservations()
        {
            var userName = User?.Identity?.Name;
            if (string.IsNullOrEmpty(userName)) return StatusCode(StatusCodes.Status400BadRequest);
            var user = await _userManager.FindByNameAsync(userName);
            if (user is null)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }

            var userReservations = await _reservationService.GetReservationByUserId(user.Id);

            return View(userReservations);
        }

        [HttpPost("{TripId:guid}/{UserId:guid}")]
        [HttpGet("{TripId:guid}/{UserId:guid}")]
        public async Task<IActionResult> DeleteReservation([FromRoute] ReservationId reservationId,[FromForm] DateTime DepartureTime)
        {
            if (DepartureTime.Equals(new DateTime()) || DateTime.Now.CompareTo(DepartureTime.AddDays(-1)) > 0)
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            return (await _reservationService.DeleteReservation(reservationId)) ?
                RedirectToAction(actionName:nameof(MyReservations), controllerName:"Trips", routeValues: new { area = "user" })
            : StatusCode(StatusCodes.Status400BadRequest)
            ;
        }
    }
}

E-Bus.Presentation/Controllers/TripsController.cs
using E_Bus.Entities.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTOs;
using ServiceContracts.DTOs.ReservationDTO;

namespace E_Bus.Presentation.Controllers
{
    [Route("[controller]/[action]")]
    public class TripsController : Controller
    {
        private readonly ITripsService _tripsService;
        private readonly IReservationService _reservationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public TripsController(ITripsService tripsService, IReservationService reservationService, UserManager<ApplicationUser> userManager)
        {
            _tripsService = tripsService;
            _reservationService = reservationService;
            _userManager = userManager;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> UpcomingTrips()
        {
            return View(await _tripsService.GetUpcomingTripsAsync());
        }

        [AllowAnonymous]
        [HttpGet("{tripId:guid}")]
        public async Task<IActionResult> TripDetails(Guid tripId)
        {
            return View(await _tripsService.GetTripByIdAsync(tripId, true));
        }

    }
}

E-Bus.Presentation/ViewComponents/QRViewComponent.cs
using IronQr;
using IronSoftware.Drawing;
using Microsoft.AspNetCore.Mvc;
using ServiceContracts.DTOs;

namespace E_Bus.Presentation.ViewComponents
{
    [ViewComponent]
    public class QRViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(UserTripWrapperModel userTripWrapperModel)
        {
            string ticketDetails = $"{userTripWrapperModel.TheUserDTO.FullName}/{userTripWrapperModel.TheUserDTO.NationalID}/{userTripWrapperModel.TheUserDTO.PhoneNumber}"+
                $"/{userTripWrapperModel.TheUserDTO.Email}/{userTripWrapperModel.TheTripResponse.Id}/Departure : {userTripWrapperModel.TheTripResponse.Starting}" +
                $"/Arrival : {userTripWrapperModel.TheTripResponse.Ending}";
            QrCode myQr = QrWriter.Write(ticketDetails);
            // Save QR Code as a Bitmap
            string qrImage = myQr.ToHtmlTag();
            // Save QR Code Bitmap as File
            //qrImage.SaveAs("qrCode.png");

            return View(model:qrImage);
        }
    }
}

E-Bus.Presentation/Areas/User/Views/Trips/MyReservations.cshtml
@model List<ReservationResponse>
@{
    ViewBag.Title = "My Reservations";
}

<div class="flexColumn center-page">
    @if (Model is null || !Model.Any())
    {
        <span style="text-align:center" class="text-red text-largeBolded">No reservations</span>

    }
    else
    {
        <table class="table table-striped m-5">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Reservation Time</th>
                    <th scope="col">Trip (Departure - Arrival)</th>
                    <th scope="col">Options</th>
                </tr>
            </thead>
            <tbody>
                @foreach (ReservationResponse reservationResponse in Model)
                {
                    <tr>
                        <th scope="row">@(Model.IndexOf(reservationResponse) + 1)</th>
                        <td>@reservationResponse.ReservationTime</td>
                        <td>@reservationResponse.TheTripResponse?.Starting - @reservationResponse.TheTripResponse?.Ending</td>
                        <td>
                            <div class="flexRow">
                            <a role="button" class="btn btn-outline-success" asp-area="user" asp-controller="Trips" asp-action="ShowReservation" asp-route-UserId="@reservationResponse.TheUserDTO.UserId" asp-route-TripId="@reservationResponse.TheTripResponse.Id">Show</a>
                            @if (DateTime.Now.CompareTo(Convert.ToDateTime(@reservationResponse.TheTripResponse.DepartureTime).AddDays(-1)) <= 0)
                            {

                                
                                <form method="post" asp-controller="Trips" asp-action="DeleteReservation" asp-route-TripId="@reservationResponse.TheTripResponse.Id" asp-route-UserId="@reservationResponse.TheUserDTO.UserId" asp-area="user">
                                        <input type="hidden" name="DepartureTime" value="@reservationResponse.TheTripResponse.DepartureTime" />
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                </form>

                            }
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

E-Bus.Presentation/Areas/User/Views/Trips/RegisterTrip.cshtml
@model ReservationResponse

@{
    ViewBag.Title = "Register Trip";
}
<div class="flexColumn center-page bordering p-4">
    @if (ViewBag.Errors is not null)
    {
        <p class="text-red text-largeBolded">@ViewBag.Errors</p>
        <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index" role="button">Go to Home</a>
    }
    else
    {
      

        {
            await Html.RenderPartialAsync(partialViewName: "_ReservationPartialView", model: Model);
        }
        <form asp-controller="Trips" asp-action="RegisterPostTrip" asp-area="user" method="post">
            <input type="hidden" name="UserId" value="@Model.TheUserDTO.UserId" />
            <input type="hidden" name="TripId" value="@Model.TheTripResponse.Id" />
            <input type="hidden" name="ReservationTime" value="@(DateTime.Now)" />

            @if (ViewBag.Errors != null)
            {
                <div class="text-red m-2">
                    <span>@ViewBag.Errors</span>
                </div>
            }
            <div class="flexRow center-page">
                <button type="submit" class="btn btn-outline-success">Submit</button>
                <a class="btn btn-outline-danger" asp-controller="Trips" asp-action="UpcomingTrips" asp-area="" role="button">Cancel</a>
            </div>

        </form>
    }
</div>

E-Bus.Presentation/Areas/User/Views/Trips/ShowPdf.cshtml
@model ReservationResponse
@{
    Layout = null;
}
<link rel="stylesheet" href="@($"https://{Context.Request.Host}/PDFStyleSheet.css")" />
<title>Ticket PDF</title>
<div class="flexColumn center-page">
    <p class="title">E-Bus Ticket</p>
    <table width="80%" height="65%" class="center">
        <tr>
            <th>Name</th>
            <td colspan="2">@Model.TheUserDTO.FullName</td>
        </tr>
        <tr>
            <th>National ID</th>
            <td colspan="2"> @Model.TheUserDTO.NationalID</td>
        </tr>
        <tr>
            <th>Trip ID</th>
            <td colspan="2"> @Model.TheTripResponse.Id</td>
        </tr>
        <tr>
            <th rowspan="2">Trip</th>
            <th style="text-align:center">Starting</th>
            <td> @Model.TheTripResponse.Starting</td>
        </tr>
        <tr>
            <th style="text-align:center">Ending</th>
            <td> @Model.TheTripResponse.Ending</td>
        </tr>
        <tr>
            <th>Transportation Mean</th>
            <td colspan="2">@Model.TheTripResponse.ServiceTypeName</td>
        </tr>
        <tr>
            <th>Ticket</th>
            <td colspan="2">@Model.TheTripResponse.Ticket EGP</td>
        </tr>
        <tr>
            <th>Departure Time</th>
            <td colspan="2">@Model.TheTripResponse.DepartureTime</td>
        </tr>
        <tr>
            <th>Arrival Time</th>
            <td colspan="2">@Model.TheTripResponse.ArrivalTime</td>
        </tr>

    </table>
    <div style="text-align:center">
        @await Component.InvokeAsync("QR", Model)
    </div>
</div>

E-Bus.Presentation/Areas/User/Views/Trips/ShowReservation.cshtml
@model ReservationResponse
@{
    ViewBag.Title = "Successful Registration";
}
<div class="flexColumn bordering center-page p-4">
    <p class="title">Reservation Details</p>

    @{
        await Html.RenderPartialAsync(partialViewName: "_ReservationPartialView", model: Model);
    }


    @await Component.InvokeAsync("QR", Model)

    <div class="flexRow center-page">
        <a class="btn btn-outline-success" asp-controller="Trips" asp-action="ShowPdf" asp-route-TripId="@Model.TheTripResponse.Id" asp-route-UserId="@Model.TheUserDTO.UserId" asp-area="user" role="button">Print</a>
        @if (DateTime.Now.CompareTo(Convert.ToDateTime(Model.TheTripResponse.DepartureTime).AddDays(-1)) <= 0)
        {
            <form method="post" asp-controller="Trips" asp-action="DeleteReservation" asp-route-TripId="@Model.TheTripResponse.Id" asp-route-UserId="@Model.TheUserDTO.UserId" asp-area="user">
                <input type="hidden" name="DepartureTime" value="@Model.TheTripResponse.DepartureTime"/>
                <button type="submit" class="btn btn-outline-danger">Delete</button>
            </form>
        }
        <a class="btn btn-outline-dark" asp-area="user" asp-controller="Trips" asp-action="MyReservations" role="button">Go to My Reservations</a>
        <a class="btn btn-outline-dark" asp-area="" asp-controller="Home" asp-action="Index" role="button">Go to Home</a>
    </div>
</div>